### PR TITLE
Merge DroneChef::Drone with DroneChef::Config

### PR DESCRIPTION
**Pull request by jmccann**
I was just passing everything from DroneChef::Drone through DroneChef::Config.  Doesn't really seem to be a good reason to have them split so to reduce some complexity I merged them together.

### CODE REVIEW

**Comment by tboerger** [comment]
Does it make sense to provide some kind of official drone-ruby lib?

**Comment by jmccann** [comment]
Yes!  If one existed I'd definitely try to use it.

In the meantime how does this PR look by itself?

**Comment by jackspirou** [comment]
@jmccann @tboerger looks like there has been discussion in the gitter room around an official ruby drone library/client.  Unless we have one ready to go, I think we should move forward with this PR.  LGTM

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
