### PR TITLE
Use alpine base image, we don't need chefdk

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by tboerger** [comment]
Decreased image size from 775MB down to 237MB, awesome!

**Comment by jackspirou** [comment]
@tboerger awesome that the image size decreased, but are we sure we didn't need the chefdk for any other parts of the plugin features? @jmccann can you confirm?  Sorry if this is obvious, i'm not that familiar with chef, but I still wanted to ask.  Thanks!

**Comment by tboerger** [comment]
@jackspirou we just need berksf and knife commands, berks is part of the berkshelf gem, knife is part of the chef gem. I have verified that berks and knife can be executed successfully within that image, so this should be totally fine :)

**Comment by jmccann** [comment]
This LGTM.  If we do run into unintended consequences we can address them.  But I'm agreeing it should probably be fine.

Thanks!

**Comment by tboerger** [comment]
LGTM

**Comment by jackspirou** [comment]
@tboerger @jmccann Thanks guys :)  LGTM

**Pull request merged**
